---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: customer-permission
spec:
  template:
    metadata:
      labels:
        app: customer-permission
    spec:
      containers:
      - name: customer-permission
        image: ceuramaster/customer-permission-service:0.1.0-SNAPSHOT
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: customer-permission-service
  labels:
    app: customer-permission
spec:
  ports:
  - name: customer-permission-service-port1
    port: 8081
    targetPort: 8080
    protocol: TCP
  selector:
    app: customer-permission
