---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: event-sender
spec:
  template:
    metadata:
      labels:
        app: event-sender
    spec:
      containers:
      - name: event-sender
        image: ceuramaster/event-sender:0.1.1-SNAPSHOT
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      
