---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: event-stream-processor
spec:
  template:
    metadata:
      labels:
        app: event-stream-processor
    spec:
      initContainers:
      - name: init-wait
        image: alpine
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 kafka-service 9094 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: event-stream-processor
        image: ceuramaster/event-stream-processor:0.2.12-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVERS
          value: kafka-service:9094
        - name: CUSTOMER_SERVICE
          value: http://customer-permission-service:8081/customers
      imagePullSecrets:
        - name: regcred
