---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-rest-proxy
spec:
  template:
    metadata:
      labels:
        app: kafka-rest-proxy
        id: "1"
    spec:
      initContainers:
      - name: init-wait
        image: alpine
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 kafka-service 9094 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: kafka-rest-proxy
        image: confluentinc/cp-kafka-rest:4.1.0
        ports:
        - containerPort: 8082
        env:
        #- name: KAFKA_ADVERTISED_PORT
        #  value: "9092"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: kafka-service:9094
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        - name: KAFKA_REST_HOST_NAME
          value: kafka-rest-proxy

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-proxy-service
  labels:
    app: kafka-rest-proxy
spec:
  ports:
  - name: kafka-rest-proxy-port
    port: 8082
    protocol: TCP
  selector:
    app: kafka-rest-proxy
  type: NodePort
